# Generated by Django 4.2.7 on 2023-12-21 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_adminpost_buy_now'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycars',
            name='admin_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.adminpost'),
        ),
        migrations.AddField(
            model_name='buycars',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
    ]
